name: Blank Issue
description: Open a free-form issue when none of the templates fit.
title: "[Blank]: "
labels:
  - blank
body:
  - type: markdown
    attributes:
      value: |
        Use this template only if the other templates do not apply.
  - type: textarea
    id: details
    attributes:
      label: Issue Details
      description: Describe the issue in your own format.
      placeholder: Add context, links, logs, or any relevant information.
    validations:
      required: true