name: Bug Report
description: Report something that is broken or not working as expected.
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: What went wrong?
      placeholder: A clear and short description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List exact steps so we can reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: Describe what actually happened.
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser/OS/device or deployment environment.
      placeholder: e.g. Chrome 121 on Windows 11, Render production
    validations:
      required: false